.TH BOOBANK 1 "02 August 2010"
.SH NAME
boobank \- Bank operations
.SH SYNOPSIS
.B boobank
[\-dqv] [\-b \fIbackends\fR] [\-cnfs] \fIcommand\fR [arguments..]
.br
.B boobank
[\-\-version] [\-\-help]
.SH DESCRIPTION
.LP
Weboob provides several applications to interact with a lot of websites.

Boobank is a console application which loads the configured \fIICapBank\fR backends
and display your accounts amount.

.SH COMMANDS
.TP
\fBlist\fR
list every accounts, with the amount of money.
.TP
\fBcoming\fR \fIid\fR
display the coming operations on a specific account.

.SH OPTIONS
.SS Results options
.TP
\fB\-c\fR, \fB\-\-condition\fR \fICONDITION\fR
filter result items to display given a boolean condition
.TP
\fB\-n\fR, \fB\-\-count\fR \fICOUNT\fR
get a maximum number of results (all backends merged)
.TP
\fB\-f\fR, \fB\-\-formatter\fR \fIFORMATTER\fR
select the output formatter (htmltable,multiline,simple,table,webkit)
.TP
\fB\-s\fR, \fB\-\-select\fR \fIFIELDS\fR
select return field keys to display (comma separated)
.TP
\fB\-\-no-header\fR
do not display header
.TP
\fB\-\-no-keys\fR
do not display field keys
.SS Logging options
.TP
\fB\-d\fR, \fB\-\-debug\fR
display debug messages
.TP
\fB\-q\fR, \fB\-\-quiet\fR
display only error messages
.TP
\fB\-v\fR, \fB\-\-verbose\fR
display info messages
.SS Misc options
.TP
\fB\-b\fR, \fB\-\-backends\fR \fIbackends\fR
select backends to load
.TP
\fB\-\-version\fR
display version of \fIweboob-config\fR
.TP
\fB\-h\fR, \fB\-\-help\fR
show the help message and exit

.SH COPYRIGHT
Copyright(C) 2010 Romain Bignon
.LP
For full COPYRIGHT see COPYING file with weboob package.
.LP
.RE
.SH FILES
 "~/.weboob/backends"
