.TH MONBOOB 1 "02 August 2010"
.SH NAME
monboob \- Get messages in your Mail User Agent and answer
.SH SYNOPSIS
.B monboob
[\-dqv] [\-b \fIbackends\fR] [\-S \fIport\fR] \fIcommand\fR [arguments..]
.br
.B monboob
[\-\-version] [\-\-help]
.SH DESCRIPTION
.LP
Weboob provides several applications to interact with a lot of websites.

Monboob is a daemon application which retrieves every X seconds new messages
and send them to an email address.

Use the \fB-S\fR option to launch a SMTP server which relays mails to the backend
as a reply.

The \fBpost\fR command can also be called to answer to a specific message.

.SH COMMANDS
.TP
\fBrun\fR
run the process (it does NOT put monboob in background)
.TP
\fBpost\fR
pipe a mail with this command to parse it and post the reply to the equivalent backend

.SH CONFIGURATION
The file \fI~/.weboob/monboob\fR is the configuration of \fBmonboob\fR:

.nf
[DEFAULT]
# Interval to check new messages
interval = 300
# Domain of the *From:* email address
domain = weboob.example.com
# Recipient of emails
recipient = romain@example.com
# SMTP server to use
smtp = mail.example.org
# Send emails in HTML or in plaintext
html = 0
.fi

.SH OPTIONS
.SS Monboob options
.TP
\fB\-S\fR, \fB\-\-smtpd\fR \fI[bind:]port\fR
run a SMTP server which relays each received mails to the backend
.SS Logging options
.TP
\fB\-d\fR, \fB\-\-debug\fR
display debug messages
.TP
\fB\-q\fR, \fB\-\-quiet\fR
display only error messages
.TP
\fB\-v\fR, \fB\-\-verbose\fR
display info messages
.SS Misc options
.TP
\fB\-b\fR, \fB\-\-backends\fR \fIbackends\fR
select backends to load
.TP
\fB\-\-version\fR
display version of \fIweboob-config\fR
.TP
\fB\-h\fR, \fB\-\-help\fR
show the help message and exit

.SH COPYRIGHT
Copyright(C) 2010 Romain Bignon
.LP
For full COPYRIGHT see COPYING file with weboob package.
.LP
.RE
.SH FILES
 "~/.weboob/backends"
 "~/.weboob/monboob"
