.\" -*- coding: utf-8 -*-
.TH QCOOKBOOB 1 "03 August 2013" "qcookboob 0\&.g"
.SH NAME
qcookboob \- search recipes
.SH SYNOPSIS
.B qcookboob
[\-h] [\-dqv] [\-b \fIbackends\fR] ...
.br
.B qcookboob
[\-\-help] [\-\-version]

.SH DESCRIPTION
.LP

Qt application allowing to search recipes.

.SS Supported websites:
* 750g (750g French recipe website)
.br
* allrecipes (Allrecipes English recipe website)
.br
* cuisineaz (Cuisine AZ French recipe website)
.br
* marmiton (Marmiton French recipe website)
.br
* supertoinette (Super Toinette, la cuisine familiale French recipe website)
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-b BACKENDS\fR, \fB\-\-backends=BACKENDS\fR
what backend(s) to enable (comma separated)
.TP
\fB\-e EXCLUDE_BACKENDS\fR, \fB\-\-exclude\-backends=EXCLUDE_BACKENDS\fR
what backend(s) to exclude (comma separated)
.TP
\fB\-I\fR, \fB\-\-insecure\fR
do not validate SSL

.SH LOGGING OPTIONS
.TP
\fB\-d\fR, \fB\-\-debug\fR
display debug messages
.TP
\fB\-q\fR, \fB\-\-quiet\fR
display only error messages
.TP
\fB\-v\fR, \fB\-\-verbose\fR
display info messages
.TP
\fB\-\-logging\-file=LOGGING_FILE\fR
file to save logs
.TP
\fB\-a\fR, \fB\-\-save\-responses\fR
save every response

.SH COPYRIGHT
Copyright(C) 2013 Julien Veyssier
.LP
For full COPYRIGHT see COPYING file with weboob package.
.LP
.RE
.SH FILES
"~/.config/weboob/backends" 

"~/.config/weboob/qcookboob"

.SH SEE ALSO
Home page: http://weboob.org/applications/qcookboob
