.TH QVIDEOOB 1 "02 August 2010"
.SH NAME
qvideoob \- Search and play videos
.SH SYNOPSIS
.B qvideoob
[\-dqv] [\-b \fIbackends\fR]
.br
.B qvideoob
[\-\-version] [\-\-help]
.SH DESCRIPTION
.LP
Weboob provides several applications to interact with a lot of websites.

This graphical application can be used to search videos on \fIICapVideo\fR
backends, and to get their meta data, including their direct URL, or to play
them in an embedded frame.

.SH OPTIONS
.SS Logging options
.TP
\fB\-d\fR, \fB\-\-debug\fR
display debug messages
.TP
\fB\-q\fR, \fB\-\-quiet\fR
display only error messages
.TP
\fB\-v\fR, \fB\-\-verbose\fR
display info messages
.SS Misc options
.TP
\fB\-b\fR, \fB\-\-backends\fR \fIbackends\fR
select backends to load
.TP
\fB\-\-version\fR
display version of \fIweboob-config\fR
.TP
\fB\-h\fR, \fB\-\-help\fR
show the help message and exit

.SH COPYRIGHT
Copyright(C) 2010 Romain Bignon
.LP
For full COPYRIGHT see COPYING file with weboob package.
.LP
.RE
.SH FILES
 "~/.weboob/backends"
