.TH QVIDEOOB 1 "14 March 2012" "qvideoob 0\&.b"
.SH NAME
qvideoob
.SH SYNOPSIS
.B qvideoob
[\-h] [\-dqv] [\-b \fIbackends\fR] ...
.br
.B qvideoob
[\-\-help] [\-\-version]

.SH DESCRIPTION
.LP

Qt application allowing to search videos on various websites and play them.

.SS Supported websites:
* arte (Arte French and German TV)
.br
* canalplus (Canal Plus French TV)
.br
* cappedtv (Capped.tv demoscene website)
.br
* dailymotion (Dailymotion video streaming website)
.br
* francetelevisions (France Télévisions video website)
.br
* ina (INA French TV video archives)
.br
* nolifetv (NolifeTV French video streaming website)
.br
* radiofrance (Radios of Radio France: Inter, Info, Bleu, Culture, Musique, FIP, Le Mouv')
.br
* youjizz (YouJizz pornographic video streaming website)
.br
* youporn (YouPorn pornographic video streaming website)
.br
* youtube (YouTube video streaming website)
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-b BACKENDS\fR, \fB\-\-backends=BACKENDS\fR
what backend(s) to enable (comma separated)

.SH LOGGING OPTIONS
.TP
\fB\-d\fR, \fB\-\-debug\fR
display debug messages
.TP
\fB\-q\fR, \fB\-\-quiet\fR
display only error messages
.TP
\fB\-v\fR, \fB\-\-verbose\fR
display info messages
.TP
\fB\-\-logging\-file=LOGGING_FILE\fR
file to save logs
.TP
\fB\-a\fR, \fB\-\-save\-responses\fR
save every response

.SH COPYRIGHT
Copyright(C) 2010-2011 Romain Bignon
.LP
For full COPYRIGHT see COPYING file with weboob package.
.LP
.RE
.SH FILES
"~/.config/weboob/backends" 

"~/.config/weboob/qvideoob"

.SH SEE ALSO
Home page: http://weboob.org/applications/qvideoob
