.TH VIDEOOB-WEBSERVER 1 "08 January 2011" "videoob-webserver 0\&.5"
.SH NAME
videoob-webserver
.SH SYNOPSIS
.B videoob\-webserver
[\-h] [\-dqv] [\-b \fIbackends\fR] ...
.br
.B videoob\-webserver
[\-\-help] [\-\-version]

.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-b BACKENDS\fR, \fB\-\-backends=BACKENDS\fR
what backend(s) to enable (comma separated)

.SH LOGGING OPTIONS
.TP
\fB\-d\fR, \fB\-\-debug\fR
display debug messages
.TP
\fB\-q\fR, \fB\-\-quiet\fR
display only error messages
.TP
\fB\-v\fR, \fB\-\-verbose\fR
display info messages
.TP
\fB\-\-logging\-file=LOGGING_FILE\fR
file to save logs
.TP
\fB\-a\fR, \fB\-\-save\-responses\fR
save every response

.SH COPYRIGHT
Copyright(C) 2010 Christophe Benz
.LP
For full COPYRIGHT see COPYING file with weboob package.
.LP
.RE
.SH FILES
"~/.weboob/backends" 

"~/.weboob/videoob-webserver"
