.TH WEBOOB-CLI 1 "09 December 2010"
.SH NAME
weboob-cli
.SH SYNOPSIS
.B weboob\-cli
[\-dqv] [\-b \fIbackends\fR] [\-cnfs] \fIcapability\fR \fImethod\fR [\fIarguments\fR..]
.br
.B weboob\-cli
[\-\-help] [\-\-version]

.SH DESCRIPTION
.LP

Weboob\-Cli is a console application to call a specific method on backends which implement the given capability.

.SS Supported websites:


.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-b BACKENDS\fR, \fB\-\-backends=BACKENDS\fR
what backend(s) to enable (comma separated)

.SH LOGGING OPTIONS
.TP
\fB\-d\fR, \fB\-\-debug\fR
display debug messages
.TP
\fB\-q\fR, \fB\-\-quiet\fR
display only error messages
.TP
\fB\-v\fR, \fB\-\-verbose\fR
display info messages
.TP
\fB\-\-logging\-file=LOGGING_FILE\fR
file to save logs
.TP
\fB\-a\fR, \fB\-\-save\-responses\fR
save every response

.SH RESULTS OPTIONS
.TP
\fB\-c CONDITION\fR, \fB\-\-condition=CONDITION\fR
filter result items to display given a boolean expression
.TP
\fB\-n COUNT\fR, \fB\-\-count=COUNT\fR
get a maximum number of results (all backends merged)
.TP
\fB\-s SELECT\fR, \fB\-\-select=SELECT\fR
select result item keys to display (comma separated)

.SH FORMATTING OPTIONS
.TP
\fB\-f FORMATTER\fR, \fB\-\-formatter=FORMATTER\fR
select output formatter (csv, htmltable, multiline, simple, table, webkit)
.TP
\fB\-\-no\-header\fR
do not display header
.TP
\fB\-\-no\-keys\fR
do not display item keys

.SH COPYRIGHT
Copyright(C) 2010 Romain Bignon
.LP
For full COPYRIGHT see COPYING file with weboob package.
.LP
.RE
.SH FILES
"~/.weboob/backends" 
