#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ft=python et softtabstop=4 cinoptions=4 shiftwidth=4 ts=4 ai

"""
Copyright(C) 2010  Romain Bignon

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

"""

import sys
from weboob import Weboob
from weboob.capabilities import CAP_MAILS

class User:
    def __init__(self, username, password, email):
        self.username = username
        self.password = password
        self.email = email

class Application:
    APPNAME = 'weboob2mail'

    def __init__(self):
        self.weboob = Weboob(self.APPNAME)

    def main(self, argv):
        self.weboob.loadmodules(CAP_MAILS)

if __name__ == '__main__':
    app = Application()
    sys.exit(app.main(sys.argv))
