# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minivideo.ui'
#
# Created: Sat Apr 17 11:04:00 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MiniVideo(object):
    def setupUi(self, MiniVideo):
        MiniVideo.setObjectName("MiniVideo")
        MiniVideo.resize(464, 111)
        MiniVideo.setFrameShape(QtGui.QFrame.StyledPanel)
        MiniVideo.setFrameShadow(QtGui.QFrame.Raised)
        self.horizontalLayout = QtGui.QHBoxLayout(MiniVideo)
        self.horizontalLayout.setContentsMargins(9, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imageLabel = QtGui.QLabel(MiniVideo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLabel.sizePolicy().hasHeightForWidth())
        self.imageLabel.setSizePolicy(sizePolicy)
        self.imageLabel.setObjectName("imageLabel")
        self.horizontalLayout.addWidget(self.imageLabel)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtGui.QLabel(MiniVideo)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.titleLabel = QtGui.QLabel(MiniVideo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.titleLabel)
        self.label_8 = QtGui.QLabel(MiniVideo)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.durationLabel = QtGui.QLabel(MiniVideo)
        self.durationLabel.setObjectName("durationLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.durationLabel)
        self.label_4 = QtGui.QLabel(MiniVideo)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.authorLabel = QtGui.QLabel(MiniVideo)
        self.authorLabel.setObjectName("authorLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.authorLabel)
        self.label_2 = QtGui.QLabel(MiniVideo)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.dateLabel = QtGui.QLabel(MiniVideo)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.dateLabel)
        self.label_3 = QtGui.QLabel(MiniVideo)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.ratingLabel = QtGui.QLabel(MiniVideo)
        self.ratingLabel.setObjectName("ratingLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ratingLabel)
        self.horizontalLayout.addLayout(self.formLayout)

        self.retranslateUi(MiniVideo)
        QtCore.QMetaObject.connectSlotsByName(MiniVideo)

    def retranslateUi(self, MiniVideo):
        MiniVideo.setWindowTitle(QtGui.QApplication.translate("MiniVideo", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MiniVideo", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.titleLabel.setText(QtGui.QApplication.translate("MiniVideo", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MiniVideo", "Duration", None, QtGui.QApplication.UnicodeUTF8))
        self.durationLabel.setText(QtGui.QApplication.translate("MiniVideo", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MiniVideo", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.authorLabel.setText(QtGui.QApplication.translate("MiniVideo", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MiniVideo", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.dateLabel.setText(QtGui.QApplication.translate("MiniVideo", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MiniVideo", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.ratingLabel.setText(QtGui.QApplication.translate("MiniVideo", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

