#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ft=python et softtabstop=4 cinoptions=4 shiftwidth=4 ts=4 ai

from __future__ import absolute_import
from weboob.applications.comparoob import Comparoob


if __name__ == '__main__':
    Comparoob.run()
